version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d # populate datase
    ports:
      - "5432:5432"
    networks:
      - microservice-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservice-network
    restart: unless-stopped

  config-server:
    image: marciorochadev/config-server:latest
    container_name: config-server
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  discovery-service:
    image: marciorochadev/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network

  product-service:
    image: marciorochadev/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - config-server
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review-service:
    image: marciorochadev/review-service:latest
    container_name: review-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - config-server
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    image: marciorochadev/user-service:latest
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
      - config-server
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-network

  api-gateway:
    image: marciorochadev/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: