version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/monitoring/prometheus/config/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservice-network
    restart: unless-stopped
  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - microservice-network
    restart: unless-stopped
  
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: postgres://guest:guest@postgres:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - microservice-network
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - microservice-network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana
    restart: unless-stopped

networks:
  microservice-network:
    external: true

volumes:
  grafana: