global:
  scrape_interval: 15s
  evaluation_interval: 1m

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: [ "postgres_exporter:9100" ]